apiVersion: v1
kind: Service
metadata:
  name: gin-app
  namespace: codee-jun
  labels:
    app: gin-app  # ✅ 给 Service 打 label（必须）
spec:
  selector:
    app: gin-app
  ports:
  - name: http
    port: 8080
    targetPort: 8080