server:
  mode: "debug"
  port: 8080
  host: 0.0.0.0
  readtimeout: 60
  writetimeout: 60

log:
  level: "debug"
mysql:
  dsn: root:123456@tcp(mysql:3306)/golang_per_day?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
redis:
  addr: "redis:6379"
  password: "123456"
  db: 0
jwt:
  secret: "golang_per_day_secret_key"
  # 24h表示24小时
  expire: 24h
ratelimit:
  # 每秒放多少个令牌
  cap: 1000
  # 每秒取多少个令牌
  quantum: 1000