server:
  mode: "debug"
  port: 8080
  host: "127.0.0.1"
  readtimeout: 60
  writetimeout: 60

log:
  level: "debug"
mysql:
  dsn: root:123456@tcp(localhost:3306)/golang_per_day?charset=utf8&parseTime=True&loc=Local&timeout=10000ms
redis:
  addr: "localhost:6379"
  password: "123456"
  db: 12
jwt:
  secret: "golang_per_day_secret_key"
  # 24h表示24小时
  expire: 24h
ratelimit:
  # 每秒放多少个令牌
  cap: 1000
  # 每秒取多少个令牌
  quantum: 1000
nats:
  url: "nats://localhost:4222"
  user: "admin"
  password: "123456"
  stream:
    name: "ORDERS_STREAM"
    subjects:
      - "orders.created"
      - "orders.updated"
    storage: "file"
    max_age: "24h"